### ISSUE TITLE
Support for redmine 3.x?

### ISSUE THREAD

**Issue by ilovetacos** [Undev/redmine_my_page_queries#28]
Hi,

I wanted to ask if there are plans to make this plugin compatible for redmine v3.x?

Thank you very much.

**Comment by Prakashjoshi23** [comment]
Hello,

Is this is working for  Redmine 3.1.2? As can not see any effects after installing this plugin in my redmine.
Thanks!

**Comment by archonwang** [comment]
I  used redmine 3.2.X.

I cannot see any effcts in my redmine either. Thanks.

**Comment by charleneChen** [comment]
For me, it did working with redmine version 3.2.0

**Comment by ghost** [comment]
I've just upgraded from 2.4.7 to 3.4.2.stable.16888 and I see the following error:
```
Started GET "/my/page" for 1.2.3.4 at 2017-07-27 10:29:03 +0200
Processing by MyController#page as HTML
  Current user: ol (id=3)
  Rendered plugins/redmine_my_page_queries/app/views/my/page.html.erb within layouts/base (2.1ms)
Completed 500 Internal Server Error in 14ms (ActiveRecord: 3.2ms)

ActionView::Template::Error (No route matches {:action=>"page_layout", :controller=>"my"}):
    1: <%= stylesheet_link_tag 'my_page_queries', plugin: 'redmine_my_page_queries' %>
    2: <%= javascript_include_tag 'my_page_queries', plugin: 'redmine_my_page_queries' %>
    3: <div class="contextual">
    4:   <%= link_to l(:label_personalize_page), action: 'page_layout' %>
    5: </div>
    6: 
    7: <h2><%= l(:label_my_page) %></h2>
  plugins/redmine_my_page_queries/app/views/my/page.html.erb:4:in `_plugins_redmine_my_page_queries_app_views_my_page_html_erb__96311781543080723_74204940'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

It happens when I try to access My Page.

**Comment by raphaelwdrf** [comment]
same problem
```
Started GET "/my/page" for 127.0.0.1 at 2021-02-11 17:39:40 -0300
Processing by MyController#page as HTML
  Current user: raphael.franca (id=6)
  Rendered plugins/redmine_my_page_queries/app/views/my/page.html.erb within layouts/base (8.1ms)
Completed 500 Internal Server Error in 48ms (ActiveRecord: 12.6ms)

ActionView::Template::Error (No route matches {:action=>"page_layout", :controller=>"my"}):
    1: <%= stylesheet_link_tag 'my_page_queries', plugin: 'redmine_my_page_queries' %>
    2: <%= javascript_include_tag 'my_page_queries', plugin: 'redmine_my_page_queries' %>
    3: <div class="contextual">
    4:   <%= link_to l(:label_personalize_page), action: 'page_layout' %>
    5: </div>
    6:
    7: <h2><%= l(:label_my_page) %></h2>
  plugins/redmine_my_page_queries/app/views/my/page.html.erb:4:in `_f67159b7944440cd13d085321a964df1'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
Redmine 3.4.13
